# Generated by Django 5.0.2 on 2024-03-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('APN', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=255)),
                ('Property_State', models.CharField(max_length=5)),
                ('Property_County', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=10)),
                ('zip', models.CharField(default='', max_length=15)),
                ('acreage', models.CharField(max_length=25, null=True)),
                ('improvement_homesite_value', models.CharField(max_length=25, null=True)),
                ('improvement_non_Homesite_value', models.CharField(max_length=25, null=True)),
                ('land_homesite_value', models.CharField(max_length=25, null=True)),
                ('land_non_homesite_value', models.CharField(max_length=25, null=True)),
                ('agricultural_market_valuation', models.CharField(max_length=25, null=True)),
                ('assessed_value', models.CharField(max_length=25, null=True)),
                ('market_value', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
