# Generated by Django 5.0.2 on 2024-03-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countydata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='email',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='phone_number',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
