# Generated by Django 5.0.2 on 2024-03-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countydata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='content',
        ),
        migrations.RemoveField(
            model_name='scrapeddata',
            name='title',
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='improvement_homesite_value',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='improvement_non_Homesite_value',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='land_homesite_value',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='land_non_homesite_value',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
