# Generated by Django 5.0.2 on 2024-03-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countydata', '0002_remove_scrapeddata_content_remove_scrapeddata_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='market_value',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
