# Generated by Django 5.0.2 on 2024-03-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countydata', '0002_scrapeddata_comment_scrapeddata_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='offer_amount',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='tax_due',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
