# Generated by Django 5.0.2 on 2024-03-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countydata', '0005_scrapeddata_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='email',
            field=models.CharField(default='test@test.com', max_length=250, null=True),
        ),
    ]
